import { mockDb, isUsingLiveSupabase, supabaseAdmin } from "./supabase";
import { Profile } from "@/types/database";
import { calculateLevel } from "./mock-store";
import { cleanInstagramUsername } from "@/lib/profile/utils";

/**
 * Normalizes a Supabase profiles table row into a frontend Profile object.
 */
export function normalizeSupabaseProfile(row: any): Profile {
  const xp = typeof row.xp === "number" ? row.xp : 100;
  const levelInfo = calculateLevel(xp);

  const displayName = row.display_name || "VIBE Member";
  const vibeId = row.vibe_id || `VB2026-${Math.floor(100 + Math.random() * 900)}`;

  // Clean Instagram handle (strips URLs, query params, leading @)
  const cleanedInstagram = cleanInstagramUsername(row.instagram_username || row.instagram_id);

  // If username is empty or matches auto-generated suffix pattern (e.g. name_1234), prefer cleaned Instagram
  let username = row.username ? String(row.username).trim() : "";
  const isAutoGenerated = !username || /^[a-z0-9_]+_\d{2,4}$/i.test(username);
  if (cleanedInstagram && isAutoGenerated) {
    username = cleanedInstagram;
  } else if (!username) {
    username = (displayName.toLowerCase().replace(/[^a-z0-9]/g, "_") + "_" + (row.vibe_id ? row.vibe_id.replace(/[^0-9]/g, "").slice(0, 4) : "2026")).slice(0, 20);
  }

  const defaultAvatar = `https://api.dicebear.com/7.x/avataaars/svg?seed=${encodeURIComponent(displayName)}`;

  return {
    id: row.id,
    clerk_user_id: row.clerk_user_id,
    vibe_id: vibeId,
    display_name: displayName,
    username,
    avatar_url: row.avatar_url || defaultAvatar,
    avatar_media_id: row.avatar_media_id || null,
    email: row.email || "",
    phone: row.phone || "",
    rotaract_club: row.club || row.rotaract_club || "Rotaract District 3192",
    college: row.college || "Rotaract District 3192",
    course_year: row.course_year || "Delegate • 2026",
    instagram_username: cleanedInstagram,
    bio: row.bio || null,
    interests: Array.isArray(row.interests) ? row.interests : [],
    skills: Array.isArray(row.skills) ? row.skills : [],
    hobbies: Array.isArray(row.hobbies) ? row.hobbies : [],
    favorite_music: Array.isArray(row.favorite_music) ? row.favorite_music : [],
    favorite_movies: Array.isArray(row.favorite_movies) ? row.favorite_movies : [],
    city: row.city || "Bengaluru",
    is_discoverable: row.is_discoverable ?? true,
    xp,
    level_number: row.level_number || levelInfo.level_number,
    level_name: row.level_name || levelInfo.level_name,
    connections_count: row.connections_count ?? 0,
    posts_count: row.posts_count ?? 0,
    games_played_count: row.games_played_count ?? 0,
    registration_id: row.registration_id || null,
    profile_completed: Boolean(row.profile_completed || (row.bio && row.interests?.length > 0)),
    created_at: row.created_at || new Date().toISOString(),
    updated_at: row.updated_at || new Date().toISOString(),
  };
}

/**
 * Fetch a profile by ID, Clerk User ID, or VIBE ID.
 * Looks first in memory (mockDb), then queries Supabase if not found.
 */
export async function getProfileByIdOrClerkId(idOrClerkId: string): Promise<Profile | null> {
  if (!idOrClerkId) return null;

  // 1. Check in-memory store
  const memProfile = mockDb.getProfile(idOrClerkId) || mockDb.getProfileByClerkId(idOrClerkId);
  if (memProfile) {
    return memProfile;
  }

  // 2. Query Supabase
  if (isUsingLiveSupabase() && supabaseAdmin) {
    try {
      // Check UUID vs text search
      const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(idOrClerkId);

      let query = supabaseAdmin.from("profiles").select("*");
      if (isUuid) {
        query = query.or(`id.eq.${idOrClerkId},clerk_user_id.eq.${idOrClerkId},vibe_id.eq.${idOrClerkId}`);
      } else {
        query = query.or(`clerk_user_id.eq.${idOrClerkId},vibe_id.eq.${idOrClerkId}`);
      }

      const { data, error } = await query.maybeSingle();

      if (data && !error) {
        const normalized = normalizeSupabaseProfile(data);
        mockDb.profiles.set(normalized.id, normalized);
        mockDb.clerkToProfileMap.set(normalized.clerk_user_id, normalized.id);
        return normalized;
      }
    } catch (err) {
      console.warn("Supabase profile lookup error:", err);
    }
  }

  return null;
}

// Shared in-memory cache for discoverable profiles (60s TTL)
interface DiscoverCache {
  profiles: Profile[];
  timestamp: number;
}

let discoverCache: DiscoverCache | null = null;
const DISCOVER_CACHE_TTL_MS = 60_000;

export function invalidateDiscoverProfilesCache() {
  discoverCache = null;
}

/**
 * Fetch all discoverable profiles for attendees to browse, connect, and view.
 * Uses a 60-second shared server cache to prevent repeated Supabase egress.
 */
export async function getAllDiscoverableProfiles(excludeProfileId?: string, limitCount = 60): Promise<Profile[]> {
  const isTest = process.env.NODE_ENV === "test";

  // Check cache first (shared across all attendees)
  if (!isTest && discoverCache && Date.now() - discoverCache.timestamp < DISCOVER_CACHE_TTL_MS) {
    return discoverCache.profiles
      .filter((p) => p.id !== excludeProfileId && p.clerk_user_id !== excludeProfileId)
      .slice(0, limitCount);
  }

  const profileMap = new Map<string, Profile>();

  // 1. Pull from Supabase first
  if (isUsingLiveSupabase() && supabaseAdmin) {
    try {
      // Fetch up to 100 top profiles for the shared pool
      const query = supabaseAdmin
        .from("profiles")
        .select("id, clerk_user_id, vibe_id, display_name, username, avatar_url, avatar_media_id, email, phone, club, rotaract_club, college, course_year, instagram_username, bio, interests, skills, hobbies, city, is_discoverable, xp, level_number, level_name, connections_count, posts_count, games_played_count, registration_id, profile_completed, created_at, updated_at")
        .order("xp", { ascending: false })
        .limit(Math.max(100, limitCount));

      const { data: dbRows, error } = await query;
      if (dbRows && !error) {
        for (const row of dbRows) {
          // Exclude blank placeholder profiles with no name or details
          if (!row.display_name || (row.display_name === "VIBE Attendee" && !row.email && !row.phone && !row.club)) {
            continue;
          }

          const normalized = normalizeSupabaseProfile(row);
          profileMap.set(normalized.id, normalized);
          mockDb.profiles.set(normalized.id, normalized);
          mockDb.clerkToProfileMap.set(normalized.clerk_user_id, normalized.id);
        }
      }
    } catch (err) {
      console.warn("Supabase discoverable profiles query error:", err);
    }
  }

  const seenClerkIds = new Set<string>();
  const seenEmails = new Set<string>();

  for (const p of Array.from(profileMap.values())) {
    if (p.clerk_user_id) seenClerkIds.add(p.clerk_user_id);
    if (p.email) seenEmails.add(p.email.toLowerCase());
  }

  // 2. Merge with any in-memory profiles, strictly deduplicating
  for (const p of Array.from(mockDb.profiles.values())) {
    if (p.is_discoverable) {
      if (profileMap.has(p.id)) continue;
      if (p.clerk_user_id && seenClerkIds.has(p.clerk_user_id)) continue;
      if (p.email && seenEmails.has(p.email.toLowerCase())) continue;

      profileMap.set(p.id, p);
      if (p.clerk_user_id) seenClerkIds.add(p.clerk_user_id);
      if (p.email) seenEmails.add(p.email.toLowerCase());
    }
  }

  const allSorted = Array.from(profileMap.values()).sort((a, b) => b.xp - a.xp);

  if (!isTest) {
    discoverCache = { profiles: allSorted, timestamp: Date.now() };
  }

  return allSorted
    .filter((p) => p.id !== excludeProfileId && p.clerk_user_id !== excludeProfileId)
    .slice(0, limitCount);
}
